language: python
cache: pip
install:
- pip install poetry
- poetry install
script:
- "python -m pytest"

matrix:
  include:
    - name: "black"
      python: 3.6
      env:
        - TEST_CMD="black ."
  include:
    - name: "mypy"
      python: 3.6
      env:
        - TEST_CMD="mypy comment_formatter/"