language: python
cache: pip
before_deploy:
- pip install poetry
install:
- poetry install
env:
- TEST_CMD="python -m pytest"
script:
- $TEST_CMD

matrix:
  include:
    - name: "black"
      python: 3.6
      env:
        - TEST_CMD="black ."